import type { Metadata } from "next";
import AuthProvider from "./components/AuthProvider";
import "./globals.css";



export const metadata: Metadata = {
  title: "Gango Rechishona",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="main-font px-3">
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
